FROM rocker/tidyverse:3.6.2
RUN R -e 'install.packages("remotes")'
RUN R -e 'remotes::install_github("r-lib/remotes", ref = "97bbf81")'
RUN R -e 'remotes::install_cran("DBI")'
RUN R -e 'remotes::install_cran("cli")'
RUN R -e 'remotes::install_cran("yaml")'
RUN R -e 'remotes::install_cran("pool")'
RUN R -e 'remotes::install_cran("httr")'
RUN R -e 'remotes::install_cran("xml2")'
RUN R -e 'remotes::install_cran("golem")'
RUN R -e 'remotes::install_cran("dplyr")'
RUN R -e 'remotes::install_cran("tidyr")'
RUN R -e 'remotes::install_cran("purrr")'
RUN R -e 'remotes::install_cran("rvest")'
RUN R -e 'remotes::install_cran("readr")'
RUN R -e 'remotes::install_cran("waiter")'
RUN R -e 'remotes::install_cran("tibble")'
RUN R -e 'remotes::install_cran("plumber")'
RUN R -e 'remotes::install_cran("countup")'
RUN R -e 'remotes::install_cran("magrittr")'
RUN R -e 'remotes::install_cran("jsonlite")'
RUN R -e 'remotes::install_cran("tidyselect")'
RUN R -e 'remotes::install_cran("htmlwidgets")'
RUN R -e 'remotes::install_cran("glue")'
RUN R -e 'remotes::install_cran("htmltools")'
RUN R -e 'remotes::install_cran("markdown")'
RUN R -e 'remotes::install_cran("rmarkdown")'
RUN R -e 'remotes::install_cran("pkgload")'
COPY inndxweb_*.tar.gz /app.tar.gz
RUN R -e 'remotes::install_local("/app.tar.gz")'
EXPOSE 3838
CMD  ["R", "-e", "options('shiny.port'=3838,shiny.host='0.0.0.0'); inndxweb::run_app()"]
